# Kubernetes Namespace and Resources for Anti-Bot Security Framework
apiVersion: v1
kind: Namespace
metadata:
  name: antibot-security
  labels:
    name: antibot-security
    environment: production
    component: security
---
# Resource Quotas
apiVersion: v1
kind: ResourceQuota
metadata:
  name: antibot-quota
  namespace: antibot-security
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "10"
    configmaps: "20"
---
# Network Policies for Security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: antibot-network-policy
  namespace: antibot-security
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    - podSelector:
        matchLabels:
          app: kong
    ports:
    - protocol: TCP
      port: 8000
    - protocol: TCP
      port: 8001
    - protocol: TCP
      port: 8002
    - protocol: TCP
      port: 8003
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: redis
    ports:
    - protocol: TCP
      port: 6379
  - to:
    - podSelector:
        matchLabels:
          app: mongodb
    ports:
    - protocol: TCP
      port: 27017
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---
# Priority Classes for Pod Scheduling
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: antibot-critical
value: 1000
globalDefault: false
description: "Priority class for critical anti-bot components"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: antibot-high
value: 500
globalDefault: false
description: "Priority class for high-priority anti-bot components"
---
# Service Account with RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: antibot-service-account
  namespace: antibot-security
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: antibot-role
  namespace: antibot-security
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: antibot-role-binding
  namespace: antibot-security
subjects:
- kind: ServiceAccount
  name: antibot-service-account
  namespace: antibot-security
roleRef:
  kind: Role
  name: antibot-role
  apiGroup: rbac.authorization.k8s.io