# Prometheus Configuration for ML Risk Scoring Engine
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # ML Risk Scoring Engine metrics
  - job_name: 'ml-risk-engine'
    static_configs:
      - targets: ['ml-risk-engine:8001']
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    
  # Redis metrics (if redis_exporter is used)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
    
  # MongoDB metrics (if mongodb_exporter is used)  
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alerting rules for ML system
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Example alerting rules (uncomment and customize as needed)
# rule_files:
#   - ml_alerts.yml