version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contractors
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./docker-data/mongo:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./docker-data/minio:/data

version: '3.8'

services:
  android-dev-tools:
    image: thyrlian/android-sdk:latest
    container_name: android-dev-tools
    volumes:
      - android-sdk-data:/opt/android-sdk
      - ./projects:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
    stdin_open: true
    tty: true
    command: /bin/bash

  gradle-cache:
    image: gradle:7.6-jdk11
    container_name: gradle-build
    volumes:
      - gradle-cache:/home/gradle/.gradle
      - ./projects:/workspace
    working_dir: /workspace
    command: tail -f /dev/null

volumes:
  android-sdk-data:
  gradle-cache: