app = "clm-realtime-service-xy7p2"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 4005
  processes = ["app"]
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  [services.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 300
  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    method = "get"
    path = "/health"
    protocol = "http"

