groups:
  - name: antibot_security_alerts
    rules:
      # High-level system alerts
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 90% for more than 5 minutes on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected on {{ $labels.instance }}"
          description: "Memory usage is above 90% on {{ $labels.instance }}"

      - alert: DiskSpaceRunningOut
        expr: (1 - node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Disk space running low on {{ $labels.instance }}"
          description: "Disk usage is above 85% on {{ $labels.instance }} ({{ $labels.mountpoint }})"

  - name: ml_risk_engine_alerts
    rules:
      # ML Risk Engine performance alerts
      - alert: MLEngineHighLatency
        expr: histogram_quantile(0.95, rate(ml_request_duration_seconds_bucket[5m])) > 0.05
        for: 2m
        labels:
          severity: critical
          service: ml-risk-engine
        annotations:
          summary: "ML Risk Engine high latency detected"
          description: "95th percentile latency is above 50ms for model {{ $labels.model_version }}"

      - alert: MLEngineHighErrorRate
        expr: rate(ml_requests_total{status!="success"}[5m]) / rate(ml_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
          service: ml-risk-engine
        annotations:
          summary: "ML Risk Engine high error rate"
          description: "Error rate is above 5% for model {{ $labels.model_version }}"

      - alert: MLModelAccuracyDrop
        expr: ml_model_accuracy < 0.90
        for: 5m
        labels:
          severity: critical
          service: ml-risk-engine
        annotations:
          summary: "ML model accuracy drop detected"
          description: "Model {{ $labels.model_version }} accuracy dropped to {{ $value }}"

      - alert: MLFeatureDrift
        expr: ml_feature_drift_score > 0.3
        for: 10m
        labels:
          severity: warning
          service: ml-risk-engine
        annotations:
          summary: "Feature drift detected"
          description: "Feature {{ $labels.feature_name }} drift score: {{ $value }}"

      - alert: MLFalsePositiveRateHigh
        expr: ml_false_positive_rate > 0.02
        for: 5m
        labels:
          severity: warning
          service: ml-risk-engine
        annotations:
          summary: "High false positive rate detected"
          description: "False positive rate is {{ $value }} for model {{ $labels.model_version }}"

  - name: security_alerts
    rules:
      # Security-specific alerts
      - alert: BotAttackSurge
        expr: rate(ml_requests_total{status="success"}[5m]) > 100 and increase(ml_risk_score_distribution_bucket{le="0.8"}[5m]) / increase(ml_risk_score_distribution_count[5m]) < 0.1
        for: 1m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Potential bot attack surge detected"
          description: "High volume of requests with low human-like scores detected"

      - alert: SecurityServiceDown
        expr: up{job=~"security-monitor|ml-risk-engine"} == 0
        for: 1m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Security service is down"
          description: "{{ $labels.job }} service is not responding"

      - alert: AnomalyDetectionTriggered
        expr: increase(security_anomaly_events_total[5m]) > 10
        for: 1m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "Multiple anomalies detected"
          description: "{{ $value }} anomaly events detected in the last 5 minutes"

      - alert: ThreatIntelligenceAlert
        expr: increase(threat_intelligence_matches_total[1m]) > 5
        for: 1m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Threat intelligence matches detected"
          description: "{{ $value }} threat intelligence matches in the last minute"

  - name: infrastructure_alerts
    rules:
      # Infrastructure service alerts
      - alert: RedisDown
        expr: up{job="redis-exporter"} == 0
        for: 1m
        labels:
          severity: critical
          service: redis
        annotations:
          summary: "Redis is down"
          description: "Redis service is not responding"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis memory usage is above 90%"

      - alert: ElasticsearchDown
        expr: up{job="elasticsearch"} == 0
        for: 2m
        labels:
          severity: critical
          service: elasticsearch
        annotations:
          summary: "Elasticsearch is down"
          description: "Elasticsearch service is not responding"

      - alert: ElasticsearchClusterRed
        expr: elasticsearch_cluster_health_status{color="red"} == 1
        for: 2m
        labels:
          severity: critical
          service: elasticsearch
        annotations:
          summary: "Elasticsearch cluster status is red"
          description: "Elasticsearch cluster health is critical"

      - alert: VaultServiceDown
        expr: up{job="infrastructure", instance=~".*vault.*"} == 0
        for: 2m
        labels:
          severity: critical
          service: vault
        annotations:
          summary: "Vault service is down"
          description: "HashiCorp Vault service is not responding"

  - name: application_performance_alerts
    rules:
      # Application performance monitoring
      - alert: HighRequestVolume
        expr: rate(http_requests_total[5m]) > 1000
        for: 5m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High request volume detected"
          description: "Request rate is {{ $value }} req/sec"

      - alert: ResponseTimeP99High
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m])) > 1.0
        for: 5m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High 99th percentile response time"
          description: "99th percentile response time is {{ $value }}s"

      - alert: WorkerQueueBacklog
        expr: worker_queue_length > 1000
        for: 5m
        labels:
          severity: warning
          service: worker
        annotations:
          summary: "Worker queue backlog detected"
          description: "Worker queue length is {{ $value }}"

      - alert: FailedTasksHigh
        expr: rate(worker_tasks_failed_total[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: worker
        annotations:
          summary: "High rate of failed tasks"
          description: "Failed task rate is {{ $value }} failures/sec"

  - name: business_metrics_alerts
    rules:
      # Business and operational metrics
      - alert: ConversionRateDrop
        expr: (rate(successful_verifications_total[1h]) / rate(verification_attempts_total[1h])) < 0.7
        for: 10m
        labels:
          severity: warning
          service: business
        annotations:
          summary: "Verification conversion rate drop"
          description: "Verification success rate dropped to {{ $value }}"

      - alert: UserExperienceDegradation
        expr: avg_over_time(user_satisfaction_score[1h]) < 7.0
        for: 15m
        labels:
          severity: warning
          service: business
        annotations:
          summary: "User experience degradation detected"
          description: "Average user satisfaction score: {{ $value }}"

      - alert: ApiRateLimitReached
        expr: rate(api_rate_limit_exceeded_total[5m]) > 5
        for: 2m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "API rate limits frequently exceeded"
          description: "Rate limit exceeded {{ $value }} times/sec"