# SMS Service Configuration
service:
  name: sms-service
  version: "1.0.0"
  environment: production
  
# Redis Configuration
redis:
  url: redis://redis:6379/0
  max_connections: 100
  socket_keepalive: true
  socket_keepalive_options:
    1: 1
    2: 3
    3: 5
  retry_on_timeout: true
  health_check_interval: 30
  connection_timeout: 10
  socket_timeout: 10

# RabbitMQ Configuration  
rabbitmq:
  url: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
  exchange: sms_exchange
  queue_prefix: sms
  max_priority: 10
  heartbeat: 600
  blocked_connection_timeout: 300
  prefetch_count: 10
  connection_attempts: 5
  retry_delay: 5

# SMS Provider Configuration
providers:
  twilio:
    enabled: true
    priority: 1
    timeout: 30
    max_retries: 3
    phone_pool_enabled: true
    phone_pool_cooldown_hours: 24
    
  aws_sns:
    enabled: true
    priority: 2
    timeout: 30
    max_retries: 3
    region: us-east-1

# Rate Limiting
rate_limiting:
  per_phone_number: 5
  window_seconds: 300
  global_per_second: 100
  burst_limit: 20

# Circuit Breaker Configuration
circuit_breaker:
  failure_threshold: 10
  timeout_seconds: 30
  half_open_max_calls: 5
  half_open_timeout: 10

# Queue Configuration
queues:
  priority_levels: 5
  message_ttl_seconds: 3600
  dead_letter_ttl_seconds: 86400
  max_retries: 3
  retry_delays:
    - 30    # First retry after 30 seconds
    - 300   # Second retry after 5 minutes  
    - 900   # Third retry after 15 minutes

# Monitoring and Observability
monitoring:
  prometheus_enabled: true
  metrics_port: 8003
  health_check_interval: 30
  log_level: INFO
  structured_logging: true
  
  # Metrics to track
  metrics:
    - sms_requests_total
    - sms_request_duration_seconds
    - circuit_breaker_state
    - queue_size
    - rate_limit_hits_total
    - worker_messages_processed_total
    - worker_processing_duration_seconds
    - worker_queue_lag_seconds

# Security Configuration
security:
  api_key_header: X-API-Key
  cors_origins:
    - "*"
  cors_methods:
    - GET
    - POST
    - PUT
    - DELETE
  cors_headers:
    - "*"

# Performance Tuning
performance:
  worker_processes: 2
  worker_connections: 1000
  keepalive_timeout: 65
  client_max_body_size: "1M"
  
  # Connection pooling
  connection_pool_size: 20
  connection_pool_max_overflow: 30
  connection_pool_timeout: 30
  
  # Async settings
  async_workers: 4
  async_timeout: 30

# Development Settings
development:
  debug: false
  reload: false
  mock_providers: false
  log_requests: true
  log_responses: false

# Alerting Configuration
alerting:
  enabled: true
  webhook_url: ""
  slack_webhook: ""
  
  # Alert conditions
  conditions:
    high_error_rate:
      threshold: 0.05  # 5%
      window_minutes: 5
      
    queue_backup:
      threshold: 1000
      window_minutes: 10
      
    circuit_breaker_open:
      threshold: 1
      immediate: true
      
    rate_limit_exceeded:
      threshold: 100
      window_minutes: 1

# Backup and Recovery
backup:
  redis_snapshots:
    enabled: true
    interval_hours: 6
    retention_days: 7
    
  message_archival:
    enabled: true
    retention_days: 30
    archive_location: "/var/log/sms/archive"