name: Farm Smoke Test

on:
  workflow_dispatch:
    inputs:
      hosts:
        description: "Comma-separated farm hosts (host:port)"
        required: false
        default: ""

jobs:
  farm-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
      - name: Run boot checks
        env:
          FLY_ANDROID_HOSTS: ${{ github.event.inputs.hosts }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        run: |
          python automation/boot_checks.py --check adb,sms,redis --json || exit 1

